import { Menu } from "@/types/menu";

const menuData: Menu[] = [
  {
    id: 0,
    keyType: "NONE",
    note: "C",
  },
  {
    id: 1,
    title: "About Me",
    scrollPos: "aboutme",
    keyType: "LEFT",
    note: "B",
  },
  {
    id: 2,
    title: "Software/Hardware",
    scrollPos: "projects",
    keyType: "BETWEEN",
    note: "A",
  },
  {
    id: 3,  
    title: "Music/SFX",
    scrollPos: 'comingsoon',
    keyType: "BETWEEN",
    note: "G",
  },
  {
    id: 4,
    title: "Game Dev",
    scrollPos: 'comingsoon',
    keyType: "RIGHT",
    note: "F",
  },
  {
    id: 5,
    title: "Contact",
    scrollPos: "contact",
    keyType: "LEFT",
    note: "E",
  },
  {
    id: 6,
    keyType: "BETWEEN",
    note: "D",
  },
  {
    id: 7,
    keyType: "RIGHT",
    note: "C",
  },
  {
    id: 8,
    title: "About Me",
    scrollPos: "aboutme",
    keyType: "LEFT",
    note: "B",
  },
  {
    id: 9,
    title: "Software/Hardware",
    scrollPos: "projects",
    keyType: "BETWEEN",
    note: "A",
  },
  {
    id: 10,  
    title: "Music/SFX",
    scrollPos: 'comingsoon',
    keyType: "BETWEEN",
    note: "G",
  },
  {
    id: 11,
    title: "Game Dev",
    scrollPos: 'comingsoon',
    keyType: "RIGHT",
    note: "F",
  },
  {
    id: 12,
    title: "Contact",
    scrollPos: "contact",
    keyType: "LEFT",
    note: "E",
  },
  {
    id: 13,
    keyType: "BETWEEN",
    note: "D",
  },
  {
    id: 14,
    keyType: "RIGHT",
    note: "C",
  },
  {
    id: 15,
    keyType: "LEFT",
    note: "B",
  },
  {
    id: 16,
    keyType: "BETWEEN",
    note: "A",
  },
  {
    id: 17,  
    title: "About Me",
    scrollPos: "aboutme",
    keyType: "BETWEEN",
    note: "G",
  },
  {
    id: 18,
    title: "Software/Hardware",
    scrollPos: "projects",
    keyType: "RIGHT",
    note: "F",
  },
  {
    id: 19,
    title: "Music/SFX",
    scrollPos: 'comingsoon',
    keyType: "LEFT",
    note: "E",
  },
  {
    id: 20,
    title: "Game Dev",
    scrollPos: 'comingsoon',
    keyType: "BETWEEN",
    note: "D",
  },
  {
    id: 21,
    title: "Contact",
    scrollPos: "contact",
    keyType: "RIGHT",
    note: "C",
  },
  {
    id: 22,
    keyType: "LEFT",
    note: "B",
  },
  {
    id: 23,
    keyType: "BETWEEN",
    note: "A",
  },
  {
    id: 24,  
    keyType: "BETWEEN",
    note: "G",
  },
  {
    id: 25,
    keyType: "RIGHT",
    note: "F",
  },
  {
    id: 26,
    title: "About Me",
    scrollPos: "aboutme",
    keyType: "LEFT",
    note: "E",
  },
  {
    id: 27,
    keyType: "BETWEEN",
    title: "Software/Hardware",
    scrollPos: "projects",
    note: "D",
  },
  {
    id: 28,
    keyType: "RIGHT",
    title: "Music/SFX",
    scrollPos: 'comingsoon',
    note: "C",
  },
  {
    id: 22,
    title: "Game Dev",
    scrollPos: 'comingsoon',
    keyType: "LEFT",
    note: "B",
  },
  {
    id: 23,
    title: "Contact",
    scrollPos: "contact",
    keyType: "BETWEEN",
    note: "A",
  },
  {
    id: 24,  
    keyType: "BETWEEN",
    note: "G",
  },
  {
    id: 25,
    keyType: "RIGHT",
    note: "F",
  },
  {
    id: 26,
    title: "About Me",
    scrollPos: "aboutme",
    keyType: "LEFT",
    note: "E",
  },
  {
    id: 27,
    keyType: "BETWEEN",
    title: "Software/Hardware",
    scrollPos: "projects",
    note: "D",
  },
  {
    id: 28,
    keyType: "RIGHT",
    title: "Music/SFX",
    scrollPos: 'comingsoon',
    note: "C",
  },
  {
    id: 22,
    title: "Game Dev",
    scrollPos: 'comingsoon',
    keyType: "LEFT",
    note: "B",
  },
  {
    id: 23,
    title: "Contact",
    scrollPos: "contact",
    keyType: "BETWEEN",
    note: "A",
  },
  {
    id: 24,  
    keyType: "BETWEEN",
    note: "G",
  },
  {
    id: 25,
    keyType: "RIGHT",
    note: "F",
  },
  {
    id: 26,
    keyType: "LEFT",
    note: "E",
  },
  {
    id: 27,
    keyType: "BETWEEN",
    note: "D",
  },
  {
    id: 28,
    keyType: "RIGHT",
    note: "C",
  },
  {
    id: 22,
    keyType: "LEFT",
    note: "B",
  },
  {
    id: 23,
    keyType: "BETWEEN",
    note: "A",
  },
  {
    id: 24,  
    keyType: "BETWEEN",
    note: "G",
  },
  {
    id: 25,
    keyType: "RIGHT",
    note: "F",
  },
];
export default menuData;
